#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x62394C698C2739FA (git@yorhel.nl)
#
Name     : ncdu
Version  : 1.16
Release  : 9
URL      : https://dev.yorhel.nl/download/ncdu-1.16.tar.gz
Source0  : https://dev.yorhel.nl/download/ncdu-1.16.tar.gz
Source1  : https://dev.yorhel.nl/download/ncdu-1.16.tar.gz.asc
Summary  : No detailed summary available
Group    : Development/Tools
License  : MIT
Requires: ncdu-bin = %{version}-%{release}
Requires: ncdu-license = %{version}-%{release}
Requires: ncdu-man = %{version}-%{release}
BuildRequires : pkgconfig(ncurses)
BuildRequires : pkgconfig(ncursesw)

%description
ncdu 1.16
=========
DESCRIPTION
ncdu (NCurses Disk Usage) is a curses-based version of
the well-known 'du', and provides a fast way to see what
directories are using your disk space.

%package bin
Summary: bin components for the ncdu package.
Group: Binaries
Requires: ncdu-license = %{version}-%{release}

%description bin
bin components for the ncdu package.


%package license
Summary: license components for the ncdu package.
Group: Default

%description license
license components for the ncdu package.


%package man
Summary: man components for the ncdu package.
Group: Default

%description man
man components for the ncdu package.


%prep
%setup -q -n ncdu-1.16
cd %{_builddir}/ncdu-1.16

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1625669345
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1625669345
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/ncdu
cp %{_builddir}/ncdu-1.16/COPYING %{buildroot}/usr/share/package-licenses/ncdu/33810c236ab50fdbb900af9b57a8b2a3161cb201
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/ncdu

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/ncdu/33810c236ab50fdbb900af9b57a8b2a3161cb201

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/ncdu.1
