#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : ncdu
Version  : 1.14
Release  : 4
URL      : https://dev.yorhel.nl/download/ncdu-1.14.tar.gz
Source0  : https://dev.yorhel.nl/download/ncdu-1.14.tar.gz
Summary  : Disk usage analyzer with an ncurses interface
Group    : Development/Tools
License  : MIT
Requires: ncdu-bin = %{version}-%{release}
Requires: ncdu-license = %{version}-%{release}
Requires: ncdu-man = %{version}-%{release}
BuildRequires : pkgconfig(ncurses)
BuildRequires : pkgconfig(ncursesw)

%description
ncdu 1.14
=========
DESCRIPTION
ncdu (NCurses Disk Usage) is a curses-based version of
the well-known 'du', and provides a fast way to see what
directories are using your disk space.

%package bin
Summary: bin components for the ncdu package.
Group: Binaries
Requires: ncdu-license = %{version}-%{release}
Requires: ncdu-man = %{version}-%{release}

%description bin
bin components for the ncdu package.


%package license
Summary: license components for the ncdu package.
Group: Default

%description license
license components for the ncdu package.


%package man
Summary: man components for the ncdu package.
Group: Default

%description man
man components for the ncdu package.


%prep
%setup -q -n ncdu-1.14

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1549336573
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1549336573
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/ncdu
cp COPYING %{buildroot}/usr/share/package-licenses/ncdu/COPYING
%make_install

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/ncdu

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/ncdu/COPYING

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man1/ncdu.1
